apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: legacy

configMapGenerator:
- name: imagestream-config
  envs:
    - params.env

configurations:
- params.yaml

replacements:
# training-hub-universal-cpu tag 3.4
- source:
    kind: ConfigMap
    name: imagestream-config
    version: v1
    fieldPath: data.odh-training-universal-workbench-image-cpu-3-4
  targets:
  - select:
      group: image.openshift.io
      kind: ImageStream
      name: training-hub-universal-cpu
      version: v1
    fieldPaths:
    - spec.tags.0.from.name

# training-hub-universal-cpu tag 3.5
- source:
    kind: ConfigMap
    name: imagestream-config
    version: v1
    fieldPath: data.odh-training-universal-workbench-image-cpu-3-5
  targets:
  - select:
      group: image.openshift.io
      kind: ImageStream
      name: training-hub-universal-cpu
      version: v1
    fieldPaths:
    - spec.tags.1.from.name

# training-hub-universal-cuda tag 3.4
- source:
    kind: ConfigMap
    name: imagestream-config
    version: v1
    fieldPath: data.odh-training-universal-workbench-image-cuda-3-4
  targets:
  - select:
      group: image.openshift.io
      kind: ImageStream
      name: training-hub-universal-cuda
      version: v1
    fieldPaths:
    - spec.tags.0.from.name

# training-hub-universal-cuda tag 3.5
- source:
    kind: ConfigMap
    name: imagestream-config
    version: v1
    fieldPath: data.odh-training-universal-workbench-image-cuda-3-5
  targets:
  - select:
      group: image.openshift.io
      kind: ImageStream
      name: training-hub-universal-cuda
      version: v1
    fieldPaths:
    - spec.tags.1.from.name

# training-hub-universal-rocm tag 3.4
- source:
    kind: ConfigMap
    name: imagestream-config
    version: v1
    fieldPath: data.odh-training-universal-workbench-image-rocm-3-4
  targets:
  - select:
      group: image.openshift.io
      kind: ImageStream
      name: training-hub-universal-rocm
      version: v1
    fieldPaths:
    - spec.tags.0.from.name

# training-hub-universal-rocm tag 3.5
- source:
    kind: ConfigMap
    name: imagestream-config
    version: v1
    fieldPath: data.odh-training-universal-workbench-image-rocm-3-5
  targets:
  - select:
      group: image.openshift.io
      kind: ImageStream
      name: training-hub-universal-rocm
      version: v1
    fieldPaths:
    - spec.tags.1.from.name

resources:
- training-hub-universal-cpu-imagestream.yaml
- training-hub-universal-cuda-imagestream.yaml
- training-hub-universal-rocm-imagestream.yaml
